In [6]:
result = 0
for i in range(100):
    result += i
print(result)

4950


In [10]:
import array 
L = list(range(10))
A = array.array('i',L)
    #'i' is a typecode that indicates the list contains only integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np
np.array(range(5))

#unlike lists, np.array will only contain one datatype
#it will therefore convert the int => decimals
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [16]:
#to explicitly set datatype, us the "dtype" keyword
np.array([1,2,3,4.0], dtype = 'int')

array([1, 2, 3, 4])

In [17]:
#you can create multidimensional numpy arrays
np.array([range(i,i+3) for i in[2,5,6]])

array([[2, 3, 4],
       [5, 6, 7],
       [6, 7, 8]])

In [28]:
#more verbose way of doing the above
a=[]
for i in [2,5,6]:
    a.append((range(i,i+3)))
np.array(a)

array([[2, 3, 4],
       [5, 6, 7],
       [6, 7, 8]])

In [29]:
#numpy as built in functions for creating arrays from scratch
#create a length 10 array with floats
np.zeros(10,dtype = 'float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
#create multi-dimensional array filled with ones
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
#create a multi-dimensional array with specific values
np.full((3,5),80085)

array([[80085, 80085, 80085, 80085, 80085],
       [80085, 80085, 80085, 80085, 80085],
       [80085, 80085, 80085, 80085, 80085]])

In [37]:
#create an array filled with a linear sequence. 
#linear sequence is between 0 and 20 and increments at step levels = 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])